Repository AY2425S1-CS2103T-T08-1/tp, pull requests merged in 2024-10, with the labels that each got.

#21 14 add travis details
  docs/AboutUs.md
  docs/images/travisim.png
Labels: type.Chore

#52 Add function for getting tags for cryptocurrencies
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low

#57 Logic: Add placeholder address field and message usage example
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: severity.High

#55 Add Hook SearchPublicAddressCommand and associated tests
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SearchPublicAddressCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/SearchPublicAddressCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#102 Logic: Create abstract class for commands that modify a person
  src/main/java/seedu/address/logic/commands/AbstractEditCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Chore, priority.Medium

#101 Feature: add more test cases for SearchPublicAddressCommandParserTest
  src/main/java/seedu/address/logic/commands/SearchPublicAddressCommand.java
  src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPublicAddressCommandParser.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/SearchPublicAddressCommandParserTest.java
Labels: severity.Low

#110 Logic: Create functional interface for creating edited persons
  src/main/java/seedu/address/logic/commands/AbstractEditCommand.java
Labels: severity.VeryLow

#111 Public address addition
  src/main/java/seedu/address/logic/commands/AbstractEditCommand.java
  src/main/java/seedu/address/logic/commands/AddPublicAddressCommand.java
  src/main/java/seedu/address/logic/parser/AddPublicAddressCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddPublicAddressCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPublicAddressCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High
